[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python server.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = "5002" 